# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaSeleccionar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaSeleccionar(object):
    def setupUi(self, VentanaSeleccionar):
        VentanaSeleccionar.setObjectName("VentanaSeleccionar")
        VentanaSeleccionar.resize(897, 535)
        VentanaSeleccionar.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(VentanaSeleccionar)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(280, 20, 601, 501))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CSV/multimedia/vector.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaSeleccionar.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame_particular = QtWidgets.QFrame(self.centralwidget)
        self.frame_particular.setGeometry(QtCore.QRect(10, 20, 261, 501))
        self.frame_particular.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_particular.setObjectName("frame_particular")
        self.layoutWidget = QtWidgets.QWidget(self.frame_particular)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.atras = QtWidgets.QPushButton(self.layoutWidget)
        self.atras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.atras.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.atras.setObjectName("atras")
        self.verticalLayout.addWidget(self.atras)
        self.titulo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.opciones = QtWidgets.QComboBox(self.layoutWidget)
        self.opciones.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.opciones.setObjectName("opciones")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.verticalLayout.addWidget(self.opciones)
        self.seleccionar = QtWidgets.QPushButton(self.layoutWidget)
        self.seleccionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seleccionar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.seleccionar.setObjectName("seleccionar")
        self.verticalLayout.addWidget(self.seleccionar)
        self.imagen = QtWidgets.QLabel(self.layoutWidget)
        self.imagen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("CSV/multimedia/buscar_registro.png"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.verticalLayout.addWidget(self.imagen)
        self.titulo2 = QtWidgets.QLabel(self.layoutWidget)
        self.titulo2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo2.setText("")
        self.titulo2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo2.setObjectName("titulo2")
        self.verticalLayout.addWidget(self.titulo2)
        self.opciones_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.opciones_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.opciones_2.setObjectName("opciones_2")
        self.verticalLayout.addWidget(self.opciones_2)
        self.dato = QtWidgets.QLineEdit(self.layoutWidget)
        self.dato.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dato.setAlignment(QtCore.Qt.AlignCenter)
        self.dato.setObjectName("dato")
        self.verticalLayout.addWidget(self.dato)
        self.realizar = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.realizar.setFont(font)
        self.realizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.realizar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.realizar.setObjectName("realizar")
        self.verticalLayout.addWidget(self.realizar)
        self.generarinforme = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.generarinforme.setFont(font)
        self.generarinforme.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generarinforme.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.generarinforme.setObjectName("generarinforme")
        self.verticalLayout.addWidget(self.generarinforme)
        self.frame_ventana = QtWidgets.QFrame(self.centralwidget)
        self.frame_ventana.setGeometry(QtCore.QRect(0, -10, 911, 551))
        self.frame_ventana.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_ventana.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ventana.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ventana.setObjectName("frame_ventana")
        self.frame_ventana.raise_()
        self.frame_particular.raise_()
        self.tableWidget.raise_()
        VentanaSeleccionar.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaSeleccionar)
        QtCore.QMetaObject.connectSlotsByName(VentanaSeleccionar)

    def retranslateUi(self, VentanaSeleccionar):
        _translate = QtCore.QCoreApplication.translate
        VentanaSeleccionar.setWindowTitle(_translate("VentanaSeleccionar", "Buscador de Registros"))
        self.atras.setText(_translate("VentanaSeleccionar", "<-"))
        self.titulo.setText(_translate("VentanaSeleccionar", "OPCIONES DE BUSQUEDA:"))
        self.opciones.setItemText(0, _translate("VentanaSeleccionar", "TODOS"))
        self.opciones.setItemText(1, _translate("VentanaSeleccionar", "Especifico"))
        self.seleccionar.setText(_translate("VentanaSeleccionar", "SELECCIONAR OPCION"))
        self.dato.setPlaceholderText(_translate("VentanaSeleccionar", "Ingrese el dato a buscar "))
        self.realizar.setText(_translate("VentanaSeleccionar", "BUSCAR"))
        self.generarinforme.setText(_translate("VentanaSeleccionar", "GENERAR CSV DE LA BUSQUEDA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaSeleccionar = QtWidgets.QMainWindow()
    ui = Ui_VentanaSeleccionar()
    ui.setupUi(VentanaSeleccionar)
    VentanaSeleccionar.show()
    sys.exit(app.exec_())
