# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaOpciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaOpciones(object):
    def setupUi(self, VentanaOpciones):
        VentanaOpciones.setObjectName("VentanaOpciones")
        VentanaOpciones.resize(402, 219)
        VentanaOpciones.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(VentanaOpciones)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(50, 60, 311, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CSV/multimedia/vector.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaOpciones.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.elegir = QtWidgets.QPushButton(self.centralwidget)
        self.elegir.setGeometry(QtCore.QRect(50, 152, 311, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CSV/multimedia/vector.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaOpciones.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.elegir.setFont(font)
        self.elegir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.elegir.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.elegir.setObjectName("elegir")
        self.opciones = QtWidgets.QComboBox(self.centralwidget)
        self.opciones.setGeometry(QtCore.QRect(50, 110, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opciones.setFont(font)
        self.opciones.setToolTip("")
        self.opciones.setStatusTip("")
        self.opciones.setWhatsThis("")
        self.opciones.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.opciones.setObjectName("opciones")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(50, 20, 311, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.regresar.setFont(font)
        self.regresar.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.regresar.setObjectName("regresar")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 221))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.titulo.raise_()
        self.elegir.raise_()
        self.opciones.raise_()
        self.regresar.raise_()
        VentanaOpciones.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaOpciones)
        QtCore.QMetaObject.connectSlotsByName(VentanaOpciones)

    def retranslateUi(self, VentanaOpciones):
        _translate = QtCore.QCoreApplication.translate
        VentanaOpciones.setWindowTitle(_translate("VentanaOpciones", "Opciones CSV"))
        self.titulo.setText(_translate("VentanaOpciones", "MAS OPCIONES PARA EL CSV:"))
        self.elegir.setText(_translate("VentanaOpciones", "ELEGIR"))
        self.opciones.setItemText(0, _translate("VentanaOpciones", "Eliminar Columnas"))
        self.opciones.setItemText(1, _translate("VentanaOpciones", "Eliminar Registros"))
        self.opciones.setItemText(2, _translate("VentanaOpciones", "Segmentar dos CSV´s"))
        self.opciones.setItemText(3, _translate("VentanaOpciones", "Segmentar por Rangos"))
        self.opciones.setItemText(4, _translate("VentanaOpciones", "Unir dos CSV´s"))
        self.opciones.setItemText(5, _translate("VentanaOpciones", "Buscar Datos en especifico del CSV y Generar CSV"))
        self.opciones.setItemText(6, _translate("VentanaOpciones", "Elegir Columnas y Generar un CSV"))
        self.opciones.setItemText(7, _translate("VentanaOpciones", "Hacer Operaciones entre columnas"))
        self.opciones.setItemText(8, _translate("VentanaOpciones", "Referencia Cruzada"))
        self.regresar.setText(_translate("VentanaOpciones", "<--"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaOpciones = QtWidgets.QMainWindow()
    ui = Ui_VentanaOpciones()
    ui.setupUi(VentanaOpciones)
    VentanaOpciones.show()
    sys.exit(app.exec_())
