# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_eliminador.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Eliminar(object):
    def setupUi(self, Ventana_Eliminar):
        Ventana_Eliminar.setObjectName("Ventana_Eliminar")
        Ventana_Eliminar.resize(410, 307)
        Ventana_Eliminar.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Ventana_Eliminar)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 60, 341, 161))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(70, 10, 271, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CSV/multimedia/vector.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ventana_Eliminar.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(20, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.regresar.setFont(font)
        self.regresar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.regresar.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.regresar.setObjectName("regresar")
        self.opciones = QtWidgets.QComboBox(self.centralwidget)
        self.opciones.setGeometry(QtCore.QRect(100, 240, 71, 21))
        self.opciones.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.opciones.setObjectName("opciones")
        self.eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.eliminar.setGeometry(QtCore.QRect(180, 260, 115, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.eliminar.setFont(font)
        self.eliminar.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.eliminar.setObjectName("eliminar")
        self.img = QtWidgets.QLabel(self.centralwidget)
        self.img.setGeometry(QtCore.QRect(20, 230, 61, 51))
        self.img.setText("")
        self.img.setPixmap(QtGui.QPixmap("CSV/multimedia/eliminar.png"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 311))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.tableWidget.raise_()
        self.titulo.raise_()
        self.regresar.raise_()
        self.opciones.raise_()
        self.eliminar.raise_()
        self.img.raise_()
        Ventana_Eliminar.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ventana_Eliminar)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Eliminar)

    def retranslateUi(self, Ventana_Eliminar):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Eliminar.setWindowTitle(_translate("Ventana_Eliminar", "Eliminador"))
        self.titulo.setText(_translate("Ventana_Eliminar", "ELIMINADOR DE REGISTROS"))
        self.regresar.setText(_translate("Ventana_Eliminar", "<---"))
        self.eliminar.setText(_translate("Ventana_Eliminar", "ELIMINAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Eliminar = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Eliminar()
    ui.setupUi(Ventana_Eliminar)
    Ventana_Eliminar.show()
    sys.exit(app.exec_())
