# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaFuente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Fuentes(object):
    def setupUi(self, Ventana_Fuentes):
        Ventana_Fuentes.setObjectName("Ventana_Fuentes")
        Ventana_Fuentes.resize(276, 167)
        Ventana_Fuentes.setMinimumSize(QtCore.QSize(267, 167))
        Ventana_Fuentes.setMaximumSize(QtCore.QSize(276, 167))
        self.centralwidget = QtWidgets.QWidget(Ventana_Fuentes)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("multimedia/vector.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ventana_Fuentes.setWindowIcon(icon)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 281, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.regresar = QtWidgets.QPushButton(self.frame)
        self.regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.regresar.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"")
        self.regresar.setObjectName("regresar")
        self.verticalLayout.addWidget(self.regresar)
        self.titulo1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo1.setFont(font)
        self.titulo1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.titulo1.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo1.setObjectName("titulo1")
        self.verticalLayout.addWidget(self.titulo1)
        self.fuentes = QtWidgets.QFontComboBox(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fuentes.setFont(font)
        self.fuentes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fuentes.setObjectName("fuentes")
        self.verticalLayout.addWidget(self.fuentes)
        self.elegir = QtWidgets.QPushButton(self.frame)
        self.elegir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.elegir.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"")
        self.elegir.setFlat(False)
        self.elegir.setObjectName("elegir")
        self.verticalLayout.addWidget(self.elegir)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        Ventana_Fuentes.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ventana_Fuentes)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Fuentes)

    def retranslateUi(self, Ventana_Fuentes):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Fuentes.setWindowTitle(_translate("Ventana_Fuentes", "Selector de Fuentes"))
        self.regresar.setText(_translate("Ventana_Fuentes", "<--"))
        self.titulo1.setText(_translate("Ventana_Fuentes", "FUENTES:"))
        self.elegir.setText(_translate("Ventana_Fuentes", "ELEGIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Fuentes = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Fuentes()
    ui.setupUi(Ventana_Fuentes)
    Ventana_Fuentes.show()
    sys.exit(app.exec_())
