# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ejemplo_youtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(319, 204)
        self.sumar = QtWidgets.QPushButton(Form)
        self.sumar.setGeometry(QtCore.QRect(0, 120, 81, 31))
        self.sumar.setObjectName("sumar")
        self.borrar = QtWidgets.QPushButton(Form)
        self.borrar.setGeometry(QtCore.QRect(230, 120, 81, 31))
        self.borrar.setObjectName("borrar")
        self.num1 = QtWidgets.QLineEdit(Form)
        self.num1.setGeometry(QtCore.QRect(90, 10, 151, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.num1.setFont(font)
        self.num1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.num1.setAutoFillBackground(False)
        self.num1.setInputMask("")
        self.num1.setText("")
        self.num1.setDragEnabled(False)
        self.num1.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QLineEdit(Form)
        self.num2.setGeometry(QtCore.QRect(90, 40, 151, 21))
        self.num2.setObjectName("num2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 70, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.sumar_2 = QtWidgets.QPushButton(Form)
        self.sumar_2.setGeometry(QtCore.QRect(230, 160, 81, 31))
        self.sumar_2.setObjectName("sumar_2")
        self.multi = QtWidgets.QPushButton(Form)
        self.multi.setGeometry(QtCore.QRect(0, 160, 81, 31))
        self.multi.setObjectName("multi")
        self.resta = QtWidgets.QPushButton(Form)
        self.resta.setGeometry(QtCore.QRect(120, 120, 81, 31))
        self.resta.setObjectName("resta")
        self.division = QtWidgets.QPushButton(Form)
        self.division.setGeometry(QtCore.QRect(120, 160, 81, 31))
        self.division.setObjectName("division")
        self.calcu2 = QtWidgets.QLabel(Form)
        self.calcu2.setGeometry(QtCore.QRect(10, 20, 51, 41))
        self.calcu2.setText("")
        self.calcu2.setPixmap(QtGui.QPixmap("CALCU.ICO"))
        self.calcu2.setScaledContents(True)
        self.calcu2.setObjectName("calcu2")
        self.calcu1 = QtWidgets.QLabel(Form)
        self.calcu1.setGeometry(QtCore.QRect(260, 20, 51, 41))
        self.calcu1.setText("")
        self.calcu1.setPixmap(QtGui.QPixmap("CALCU.ICO"))
        self.calcu1.setScaledContents(True)
        self.calcu1.setObjectName("calcu1")

        self.retranslateUi(Form)
        self.borrar.clicked.connect(self.num1.clear)
        self.borrar.clicked.connect(self.num2.clear)
        self.sumar_2.clicked.connect(Form.close)
        self.borrar.clicked.connect(self.label.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sumar.setText(_translate("Form", "Sumar"))
        self.borrar.setText(_translate("Form", "Borrar"))
        self.num1.setPlaceholderText(_translate("Form", "Ingresa el numero 1"))
        self.num2.setPlaceholderText(_translate("Form", "Ingresa el numero 2"))
        self.sumar_2.setText(_translate("Form", "Salir"))
        self.multi.setText(_translate("Form", "Multiplicacion"))
        self.resta.setText(_translate("Form", "Resta"))
        self.division.setText(_translate("Form", "Division"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
