# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selecciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(427, 248)
        Form.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.titulo = QtWidgets.QLabel(Form)
        self.titulo.setGeometry(QtCore.QRect(60, 30, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 210, 75, 23))
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.borrar = QtWidgets.QPushButton(Form)
        self.borrar.setGeometry(QtCore.QRect(270, 210, 75, 23))
        self.borrar.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.borrar.setObjectName("borrar")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 90, 381, 91))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prograW = QtWidgets.QListWidget(self.widget)
        self.prograW.setObjectName("prograW")
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.prograW.addItem(item)
        self.horizontalLayout.addWidget(self.prograW)
        self.lenguajesA = QtWidgets.QListWidget(self.widget)
        self.lenguajesA.setObjectName("lenguajesA")
        self.horizontalLayout.addWidget(self.lenguajesA)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(20, 58, 381, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl1 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl1.setFont(font)
        self.lbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1.setObjectName("lbl1")
        self.horizontalLayout_2.addWidget(self.lbl1)
        self.lbl2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl2.setFont(font)
        self.lbl2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl2.setObjectName("lbl2")
        self.horizontalLayout_2.addWidget(self.lbl2)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        self.borrar.clicked.connect(self.lenguajesA.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo.setText(_translate("Form", "¿Que Lenguajes sabes?"))
        self.pushButton.setText(_translate("Form", "SALIR"))
        self.borrar.setText(_translate("Form", "BORRAR"))
        __sortingEnabled = self.prograW.isSortingEnabled()
        self.prograW.setSortingEnabled(False)
        item = self.prograW.item(0)
        item.setText(_translate("Form", "1-Java"))
        item = self.prograW.item(1)
        item.setText(_translate("Form", "2-JavaScript"))
        item = self.prograW.item(2)
        item.setText(_translate("Form", "3-PHP"))
        item = self.prograW.item(3)
        item.setText(_translate("Form", "4-Python"))
        item = self.prograW.item(4)
        item.setText(_translate("Form", "5-Ruby"))
        item = self.prograW.item(5)
        item.setText(_translate("Form", "6-C++"))
        item = self.prograW.item(6)
        item.setText(_translate("Form", "7-C#"))
        item = self.prograW.item(7)
        item.setText(_translate("Form", "8-Perl"))
        item = self.prograW.item(8)
        item.setText(_translate("Form", "9-HTML"))
        self.prograW.setSortingEnabled(__sortingEnabled)
        self.lbl1.setText(_translate("Form", "Programacion Web"))
        self.lbl2.setText(_translate("Form", "Lenguajes Aprendidos:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
