# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(203, 287)
        self.esconder = QtWidgets.QPushButton(Form)
        self.esconder.setGeometry(QtCore.QRect(120, 170, 75, 23))
        self.esconder.setObjectName("esconder")
        self.mostrar = QtWidgets.QPushButton(Form)
        self.mostrar.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.mostrar.setObjectName("mostrar")
        self.usuario = QtWidgets.QLineEdit(Form)
        self.usuario.setGeometry(QtCore.QRect(30, 100, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usuario.setFont(font)
        self.usuario.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.usuario.setTabletTracking(False)
        self.usuario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.usuario.setClearButtonEnabled(False)
        self.usuario.setObjectName("usuario")
        self.contra = QtWidgets.QLineEdit(Form)
        self.contra.setGeometry(QtCore.QRect(30, 130, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.contra.setFont(font)
        self.contra.setEchoMode(QtWidgets.QLineEdit.Password)
        self.contra.setObjectName("contra")
        self.imprimir = QtWidgets.QPushButton(Form)
        self.imprimir.setGeometry(QtCore.QRect(60, 200, 81, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mutimedia/IMPRIME.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imprimir.setIcon(icon)
        self.imprimir.setObjectName("imprimir")
        self.imagen = QtWidgets.QLabel(Form)
        self.imagen.setGeometry(QtCore.QRect(50, 10, 101, 81))
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("mutimedia/GRPUSR.ICO"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.resultado = QtWidgets.QLabel(Form)
        self.resultado.setGeometry(QtCore.QRect(10, 240, 191, 41))
        self.resultado.setText("")
        self.resultado.setPixmap(QtGui.QPixmap("IMPRIME.ICO"))
        self.resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado.setObjectName("resultado")

        self.retranslateUi(Form)
        self.mostrar.clicked.connect(self.resultado.show)
        self.esconder.clicked.connect(self.resultado.hide)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.esconder.setText(_translate("Form", "ESCONDER"))
        self.mostrar.setText(_translate("Form", "MOSTRAR"))
        self.usuario.setPlaceholderText(_translate("Form", "Ingresa tu Usuario"))
        self.contra.setPlaceholderText(_translate("Form", "Ingresa tu Contraseña"))
        self.imprimir.setText(_translate("Form", "IMPRIMIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
