# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_borrar_caracteres.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Caracteres(object):
    def setupUi(self, Ventana_Caracteres):
        Ventana_Caracteres.setObjectName("Ventana_Caracteres")
        Ventana_Caracteres.resize(298, 159)
        Ventana_Caracteres.setStyleSheet("background-color: rgb(105, 110, 200);")
        self.centralwidget = QtWidgets.QWidget(Ventana_Caracteres)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 261, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ruta = QtWidgets.QLineEdit(self.widget)
        self.ruta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ruta.setObjectName("ruta")
        self.verticalLayout.addWidget(self.ruta)
        self.hacer = QtWidgets.QPushButton(self.widget)
        self.hacer.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"\n"
"}")
        self.hacer.setObjectName("hacer")
        self.verticalLayout.addWidget(self.hacer)
        self.resultado = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.resultado.setFont(font)
        self.resultado.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resultado.setFrameShape(QtWidgets.QFrame.Box)
        self.resultado.setText("")
        self.resultado.setObjectName("resultado")
        self.verticalLayout.addWidget(self.resultado)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Ventana_Caracteres.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ventana_Caracteres)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 298, 21))
        self.menubar.setObjectName("menubar")
        Ventana_Caracteres.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ventana_Caracteres)
        self.statusbar.setObjectName("statusbar")
        Ventana_Caracteres.setStatusBar(self.statusbar)

        self.retranslateUi(Ventana_Caracteres)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Caracteres)

    def retranslateUi(self, Ventana_Caracteres):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Caracteres.setWindowTitle(_translate("Ventana_Caracteres", "Borrar Caracteres"))
        self.label.setText(_translate("Ventana_Caracteres", "BORRADOR DE DOCUMENTOS"))
        self.hacer.setText(_translate("Ventana_Caracteres", "BORRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Caracteres = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Caracteres()
    ui.setupUi(Ventana_Caracteres)
    Ventana_Caracteres.show()
    sys.exit(app.exec_())
