# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_visualidor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Visualizadora(object):
    def setupUi(self, Ventana_Visualizadora):
        Ventana_Visualizadora.setObjectName("Ventana_Visualizadora")
        Ventana_Visualizadora.resize(710, 292)
        Ventana_Visualizadora.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Ventana_Visualizadora)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 661, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(110, 10, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.regresar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        Ventana_Visualizadora.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ventana_Visualizadora)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName("menubar")
        Ventana_Visualizadora.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ventana_Visualizadora)
        self.statusbar.setObjectName("statusbar")
        Ventana_Visualizadora.setStatusBar(self.statusbar)

        self.retranslateUi(Ventana_Visualizadora)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Visualizadora)

    def retranslateUi(self, Ventana_Visualizadora):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Visualizadora.setWindowTitle(_translate("Ventana_Visualizadora", "Visualizador"))
        self.titulo.setText(_translate("Ventana_Visualizadora", "VISUALIZADOR DE TAREAS"))
        self.regresar.setText(_translate("Ventana_Visualizadora", "<---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Visualizadora = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Visualizadora()
    ui.setupUi(Ventana_Visualizadora)
    Ventana_Visualizadora.show()
    sys.exit(app.exec_())
