# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_recordatorio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Recordatorio(object):
    def setupUi(self, Ventana_Recordatorio):
        Ventana_Recordatorio.setObjectName("Ventana_Recordatorio")
        Ventana_Recordatorio.resize(520, 293)
        Ventana_Recordatorio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Ventana_Recordatorio)
        self.centralwidget.setObjectName("centralwidget")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(10, 20, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.regresar.setFont(font)
        self.regresar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(100, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.titulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.titulo_2.setGeometry(QtCore.QRect(50, 70, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.titulo_2.setFont(font)
        self.titulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_2.setObjectName("titulo_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 120, 461, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titulo_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.titulo_3.setFont(font)
        self.titulo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_3.setObjectName("titulo_3")
        self.horizontalLayout.addWidget(self.titulo_3)
        self.min = QtWidgets.QSpinBox(self.widget)
        self.min.setObjectName("min")
        self.horizontalLayout.addWidget(self.min)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.titulo_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.titulo_4.setFont(font)
        self.titulo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_4.setObjectName("titulo_4")
        self.horizontalLayout_3.addWidget(self.titulo_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titulo_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.titulo_5.setFont(font)
        self.titulo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_5.setObjectName("titulo_5")
        self.horizontalLayout_2.addWidget(self.titulo_5)
        self.veces = QtWidgets.QSpinBox(self.widget)
        self.veces.setObjectName("veces")
        self.horizontalLayout_2.addWidget(self.veces)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 160, 461, 102))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hacer = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hacer.setFont(font)
        self.hacer.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.hacer.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.hacer.setObjectName("hacer")
        self.verticalLayout.addWidget(self.hacer)
        self.mensaje = QtWidgets.QTextBrowser(self.widget1)
        self.mensaje.setEnabled(False)
        self.mensaje.setObjectName("mensaje")
        self.verticalLayout.addWidget(self.mensaje)
        Ventana_Recordatorio.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ventana_Recordatorio)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        Ventana_Recordatorio.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ventana_Recordatorio)
        self.statusbar.setObjectName("statusbar")
        Ventana_Recordatorio.setStatusBar(self.statusbar)

        self.retranslateUi(Ventana_Recordatorio)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Recordatorio)

    def retranslateUi(self, Ventana_Recordatorio):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Recordatorio.setWindowTitle(_translate("Ventana_Recordatorio", "Recordatorio de Tareas"))
        self.regresar.setText(_translate("Ventana_Recordatorio", "<---"))
        self.titulo.setText(_translate("Ventana_Recordatorio", "RECORDATORIO DE TAREAS"))
        self.titulo_2.setText(_translate("Ventana_Recordatorio", "INGRESE EL NUMERO DE MINUTOS PARA RECORDAR LAS TAREAS"))
        self.titulo_3.setText(_translate("Ventana_Recordatorio", "Minutos:"))
        self.titulo_4.setText(_translate("Ventana_Recordatorio", "X"))
        self.titulo_5.setText(_translate("Ventana_Recordatorio", "Cantidad de veces:"))
        self.hacer.setText(_translate("Ventana_Recordatorio", "ENTER"))
        self.mensaje.setHtml(_translate("Ventana_Recordatorio", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Recordatorio = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Recordatorio()
    ui.setupUi(Ventana_Recordatorio)
    Ventana_Recordatorio.show()
    sys.exit(app.exec_())
