# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_registrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaRegistrarTarea(object):
    def setupUi(self, VentanaRegistrarTarea):
        VentanaRegistrarTarea.setObjectName("VentanaRegistrarTarea")
        VentanaRegistrarTarea.resize(401, 248)
        VentanaRegistrarTarea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(VentanaRegistrarTarea)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(40, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.regresar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.limpiar.setGeometry(QtCore.QRect(40, 160, 101, 41))
        self.limpiar.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.limpiar.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.limpiar.setObjectName("limpiar")
        self.exito = QtWidgets.QLabel(self.centralwidget)
        self.exito.setGeometry(QtCore.QRect(145, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.exito.setFont(font)
        self.exito.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.exito.setText("")
        self.exito.setAlignment(QtCore.Qt.AlignCenter)
        self.exito.setObjectName("exito")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 321, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tarea = QtWidgets.QTextEdit(self.layoutWidget)
        self.tarea.setObjectName("tarea")
        self.verticalLayout.addWidget(self.tarea)
        self.doit = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.doit.setFont(font)
        self.doit.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.doit.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.doit.setObjectName("doit")
        self.verticalLayout.addWidget(self.doit)
        VentanaRegistrarTarea.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaRegistrarTarea)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 21))
        self.menubar.setObjectName("menubar")
        VentanaRegistrarTarea.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaRegistrarTarea)
        self.statusbar.setObjectName("statusbar")
        VentanaRegistrarTarea.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaRegistrarTarea)
        self.limpiar.clicked.connect(self.tarea.clear)
        QtCore.QMetaObject.connectSlotsByName(VentanaRegistrarTarea)

    def retranslateUi(self, VentanaRegistrarTarea):
        _translate = QtCore.QCoreApplication.translate
        VentanaRegistrarTarea.setWindowTitle(_translate("VentanaRegistrarTarea", "Registrar Tareas"))
        self.titulo.setText(_translate("VentanaRegistrarTarea", "AGREGAR UNA NUEVA TAREA"))
        self.regresar.setText(_translate("VentanaRegistrarTarea", "<---"))
        self.limpiar.setText(_translate("VentanaRegistrarTarea", "LIMPIAR"))
        self.doit.setText(_translate("VentanaRegistrarTarea", "REGISTRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaRegistrarTarea = QtWidgets.QMainWindow()
    ui = Ui_VentanaRegistrarTarea()
    ui.setupUi(VentanaRegistrarTarea)
    VentanaRegistrarTarea.show()
    sys.exit(app.exec_())
