# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(256, 385)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 70, 239, 310))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.numero5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero5.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero5.setObjectName("numero5")
        self.gridLayout.addWidget(self.numero5, 2, 1, 1, 1)
        self.division = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.division.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.division.setObjectName("division")
        self.gridLayout.addWidget(self.division, 5, 1, 1, 1)
        self.numero8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero8.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero8.setObjectName("numero8")
        self.gridLayout.addWidget(self.numero8, 3, 1, 1, 1)
        self.multi = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.multi.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.multi.setObjectName("multi")
        self.gridLayout.addWidget(self.multi, 5, 0, 1, 1)
        self.numero2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero2.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero2.setObjectName("numero2")
        self.gridLayout.addWidget(self.numero2, 1, 1, 1, 1)
        self.numero6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero6.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero6.setObjectName("numero6")
        self.gridLayout.addWidget(self.numero6, 2, 2, 1, 1)
        self.limpiar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.limpiar.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.limpiar.setObjectName("limpiar")
        self.gridLayout.addWidget(self.limpiar, 9, 0, 1, 3)
        self.menos = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.menos.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.menos.setObjectName("menos")
        self.gridLayout.addWidget(self.menos, 4, 1, 1, 1)
        self.numero4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero4.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero4.setObjectName("numero4")
        self.gridLayout.addWidget(self.numero4, 2, 0, 1, 1)
        self.parentesisizq = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.parentesisizq.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.parentesisizq.setObjectName("parentesisizq")
        self.gridLayout.addWidget(self.parentesisizq, 6, 1, 1, 1)
        self.numero7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero7.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero7.setObjectName("numero7")
        self.gridLayout.addWidget(self.numero7, 3, 0, 1, 1)
        self.punto = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.punto.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.punto.setObjectName("punto")
        self.gridLayout.addWidget(self.punto, 6, 0, 1, 1)
        self.mas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mas.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.mas.setObjectName("mas")
        self.gridLayout.addWidget(self.mas, 4, 0, 1, 1)
        self.numero1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero1.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero1.setObjectName("numero1")
        self.gridLayout.addWidget(self.numero1, 1, 0, 1, 1)
        self.numero9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero9.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero9.setObjectName("numero9")
        self.gridLayout.addWidget(self.numero9, 3, 2, 1, 1)
        self.numero3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero3.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero3.setObjectName("numero3")
        self.gridLayout.addWidget(self.numero3, 1, 2, 1, 1)
        self.resultado = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.resultado.setFont(font)
        self.resultado.setStyleSheet("font: 75 28pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.resultado.setFrameShape(QtWidgets.QFrame.Box)
        self.resultado.setText("")
        self.resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado.setObjectName("resultado")
        self.gridLayout.addWidget(self.resultado, 0, 0, 1, 3)
        self.numero0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.numero0.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 0);\n"
"}")
        self.numero0.setObjectName("numero0")
        self.gridLayout.addWidget(self.numero0, 4, 2, 1, 1)
        self.parentesisder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.parentesisder.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.parentesisder.setObjectName("parentesisder")
        self.gridLayout.addWidget(self.parentesisder, 5, 2, 1, 1)
        self.borraruno = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.borraruno.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.borraruno.setObjectName("borraruno")
        self.gridLayout.addWidget(self.borraruno, 6, 2, 1, 1)
        self.igual = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.igual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.igual.setMouseTracking(False)
        self.igual.setTabletTracking(False)
        self.igual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.igual.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.igual.setCheckable(False)
        self.igual.setChecked(False)
        self.igual.setAutoDefault(False)
        self.igual.setDefault(False)
        self.igual.setFlat(False)
        self.igual.setObjectName("igual")
        self.gridLayout.addWidget(self.igual, 8, 0, 1, 3)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 181, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imagen1 = QtWidgets.QLabel(self.layoutWidget)
        self.imagen1.setEnabled(False)
        self.imagen1.setAutoFillBackground(False)
        self.imagen1.setText("")
        self.imagen1.setTextFormat(QtCore.Qt.PlainText)
        self.imagen1.setPixmap(QtGui.QPixmap("multimedia/CALCU.ICO"))
        self.imagen1.setScaledContents(True)
        self.imagen1.setObjectName("imagen1")
        self.horizontalLayout.addWidget(self.imagen1)
        self.imagen2 = QtWidgets.QLabel(self.layoutWidget)
        self.imagen2.setEnabled(False)
        self.imagen2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.imagen2.setText("")
        self.imagen2.setPixmap(QtGui.QPixmap("multimedia/CALCU.ICO"))
        self.imagen2.setScaledContents(True)
        self.imagen2.setObjectName("imagen2")
        self.horizontalLayout.addWidget(self.imagen2)
        self.imagen3 = QtWidgets.QLabel(self.layoutWidget)
        self.imagen3.setEnabled(False)
        self.imagen3.setText("")
        self.imagen3.setPixmap(QtGui.QPixmap("multimedia/CALCU.ICO"))
        self.imagen3.setScaledContents(True)
        self.imagen3.setObjectName("imagen3")
        self.horizontalLayout.addWidget(self.imagen3)

        self.retranslateUi(Form)
        self.limpiar.clicked.connect(self.resultado.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.numero5.setText(_translate("Form", "5"))
        self.division.setText(_translate("Form", "/"))
        self.numero8.setText(_translate("Form", "8"))
        self.multi.setText(_translate("Form", "*"))
        self.numero2.setText(_translate("Form", "2"))
        self.numero6.setText(_translate("Form", "6"))
        self.limpiar.setText(_translate("Form", "CLEAR"))
        self.menos.setText(_translate("Form", "-"))
        self.numero4.setText(_translate("Form", "4"))
        self.parentesisizq.setText(_translate("Form", "("))
        self.numero7.setText(_translate("Form", "7"))
        self.punto.setText(_translate("Form", "."))
        self.mas.setText(_translate("Form", "+"))
        self.numero1.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.numero1.setText(_translate("Form", "1"))
        self.numero9.setText(_translate("Form", "9"))
        self.numero3.setText(_translate("Form", "3"))
        self.numero0.setText(_translate("Form", "0"))
        self.parentesisder.setText(_translate("Form", ")"))
        self.borraruno.setText(_translate("Form", "DEL"))
        self.igual.setText(_translate("Form", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
