# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lsd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaLCD(object):
    def setupUi(self, VentanaLCD):
        VentanaLCD.setObjectName("VentanaLCD")
        VentanaLCD.resize(342, 157)

        VentanaLCD.setMinimumSize(QtCore.QSize(342, 157))
        VentanaLCD.setMaximumSize(QtCore.QSize(342, 157))

        self.centralwidget = QtWidgets.QWidget(VentanaLCD)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 301, 83))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.entrada = QtWidgets.QLineEdit(self.widget)
        self.entrada.setInputMask("")
        self.entrada.setAlignment(QtCore.Qt.AlignCenter)
        self.entrada.setObjectName("entrada")
        self.verticalLayout.addWidget(self.entrada)
        self.botonpasar = QtWidgets.QPushButton(self.widget)
        self.botonpasar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonpasar.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    border:1.5px solid black;\n"
"}")
        self.botonpasar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ejercicio15_lcdNumber/img/flecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonpasar.setIcon(icon)
        self.botonpasar.setObjectName("botonpasar")
        self.verticalLayout.addWidget(self.botonpasar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pantalla = QtWidgets.QLCDNumber(self.widget)
        self.pantalla.setObjectName("pantalla")
        self.verticalLayout_2.addWidget(self.pantalla)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 110, 301, 21))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.decimal = QtWidgets.QPushButton(self.splitter)
        self.decimal.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.decimal.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(165, 175, 173);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.decimal.setObjectName("decimal")
        self.binario = QtWidgets.QPushButton(self.splitter)
        self.binario.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.binario.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(165, 175, 173);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.binario.setObjectName("binario")
        self.octagonal = QtWidgets.QPushButton(self.splitter)
        self.octagonal.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.octagonal.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(165, 175, 173);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.octagonal.setObjectName("octagonal")
        self.hexadecimal = QtWidgets.QPushButton(self.splitter)
        self.hexadecimal.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.hexadecimal.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(165, 175, 173);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.hexadecimal.setObjectName("hexadecimal")
        VentanaLCD.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaLCD)
        QtCore.QMetaObject.connectSlotsByName(VentanaLCD)

    def retranslateUi(self, VentanaLCD):
        _translate = QtCore.QCoreApplication.translate
        VentanaLCD.setWindowTitle(_translate("VentanaLCD", "Convertidor"))
        self.entrada.setPlaceholderText(_translate("VentanaLCD", "Ingresa el numero a Convertir:"))
        self.decimal.setText(_translate("VentanaLCD", "DEC"))
        self.binario.setText(_translate("VentanaLCD", "BIN"))
        self.octagonal.setText(_translate("VentanaLCD", "OCT"))
        self.hexadecimal.setText(_translate("VentanaLCD", "HEX"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaLCD = QtWidgets.QMainWindow()
    ui = Ui_VentanaLCD()
    ui.setupUi(VentanaLCD)
    VentanaLCD.show()
    sys.exit(app.exec_())
