# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ropa.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(278, 315)
        Form.setStyleSheet("background-color: rgb(200, 186, 127);")
        self.titulo = QtWidgets.QLabel(Form)
        self.titulo.setGeometry(QtCore.QRect(20, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.imagen = QtWidgets.QLabel(Form)
        self.imagen.setGeometry(QtCore.QRect(80, 40, 121, 81))
        self.imagen.setStyleSheet("")
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("multimedia/ropa.gif"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 220, 251, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl2.setStyleSheet("font: 75 8pt \"Segoe Script\";")
        self.lbl2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl2.setObjectName("lbl2")
        self.horizontalLayout_3.addWidget(self.lbl2)
        self.sb2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.sb2.setStyleSheet("font: italic 8pt \"MS Sans Serif\";")
        self.sb2.setObjectName("sb2")
        self.horizontalLayout_3.addWidget(self.sb2)
        self.resultado2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultado2.setFont(font)
        self.resultado2.setFrameShape(QtWidgets.QFrame.Box)
        self.resultado2.setText("")
        self.resultado2.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado2.setObjectName("resultado2")
        self.horizontalLayout_3.addWidget(self.resultado2)
        self.boton = QtWidgets.QPushButton(Form)
        self.boton.setGeometry(QtCore.QRect(10, 280, 75, 23))
        self.boton.setStyleSheet("QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(255, 170, 127);\n"
"}")
        self.boton.setObjectName("boton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 71, 16))
        self.label_4.setObjectName("label_4")
        self.total = QtWidgets.QLabel(Form)
        self.total.setGeometry(QtCore.QRect(190, 270, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total.setFont(font)
        self.total.setText("")
        self.total.setAlignment(QtCore.Qt.AlignCenter)
        self.total.setObjectName("total")
        self.totalboton = QtWidgets.QPushButton(Form)
        self.totalboton.setGeometry(QtCore.QRect(100, 280, 75, 23))
        self.totalboton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}")
        self.totalboton.setObjectName("totalboton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 150, 251, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl1 = QtWidgets.QLabel(self.widget)
        self.lbl1.setStyleSheet("font: 75 8pt \"Segoe Script\";")
        self.lbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1.setObjectName("lbl1")
        self.horizontalLayout.addWidget(self.lbl1)
        self.sb1 = QtWidgets.QSpinBox(self.widget)
        self.sb1.setStyleSheet("font: italic 8pt \"MS Sans Serif\";")
        self.sb1.setObjectName("sb1")
        self.horizontalLayout.addWidget(self.sb1)
        self.resultado1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultado1.setFont(font)
        self.resultado1.setAccessibleName("")
        self.resultado1.setAccessibleDescription("")
        self.resultado1.setFrameShape(QtWidgets.QFrame.Panel)
        self.resultado1.setText("")
        self.resultado1.setTextFormat(QtCore.Qt.RichText)
        self.resultado1.setScaledContents(False)
        self.resultado1.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado1.setObjectName("resultado1")
        self.horizontalLayout.addWidget(self.resultado1)

        self.retranslateUi(Form)
        self.boton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo.setText(_translate("Form", "DEPARTAMENTO DE ROPA"))
        self.lbl2.setText(_translate("Form", "$100 pesos    X"))
        self.boton.setText(_translate("Form", "Salir"))
        self.label_3.setText(_translate("Form", "PLAYERA"))
        self.label_4.setText(_translate("Form", "PANTALON"))
        self.totalboton.setText(_translate("Form", "Total"))
        self.lbl1.setText(_translate("Form", "$50 pesos     X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
