# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaCSV.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaPrincipal(object):
    def setupUi(self, VentanaPrincipal):
        VentanaPrincipal.setObjectName("VentanaPrincipal")
        VentanaPrincipal.resize(1480, 715)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VentanaPrincipal.sizePolicy().hasHeightForWidth())
        VentanaPrincipal.setSizePolicy(sizePolicy)
        VentanaPrincipal.setMinimumSize(QtCore.QSize(1480, 715))
        VentanaPrincipal.setMaximumSize(QtCore.QSize(1480, 715))
        font = QtGui.QFont()
        font.setFamily("Arial")
        VentanaPrincipal.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../multimedia/vector.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaPrincipal.setWindowIcon(icon)
        VentanaPrincipal.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(VentanaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(370, 10, 41, 441))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setStyleSheet("color: rgb(200, 82, 13);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 10, 20, 691))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 0, 1461, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 440, 1461, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(1460, 10, 20, 691))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.line_6.setFont(font)
        self.line_6.setStyleSheet("color: rgb(200, 82, 13);")
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(740, 10, 31, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.line_5.setFont(font)
        self.line_5.setStyleSheet("color: rgb(200, 82, 13);")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 690, 1461, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 30, 341, 162))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titulo2.setFont(font)
        self.titulo2.setStyleSheet("\n"
"border:none;\n"
"border-right: 5px solid gray;\n"
"border-left: 5px solid gray;")
        self.titulo2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo2.setObjectName("titulo2")
        self.verticalLayout_2.addWidget(self.titulo2)
        self.encabezados = QtWidgets.QListWidget(self.layoutWidget)
        self.encabezados.setObjectName("encabezados")
        self.verticalLayout_2.addWidget(self.encabezados)
        self.errorarchivo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("HP Simplified Light")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.errorarchivo.setFont(font)
        self.errorarchivo.setFrameShape(QtWidgets.QFrame.Box)
        self.errorarchivo.setText("")
        self.errorarchivo.setAlignment(QtCore.Qt.AlignCenter)
        self.errorarchivo.setObjectName("errorarchivo")
        self.verticalLayout_2.addWidget(self.errorarchivo)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 361, 411))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imagen = QtWidgets.QLabel(self.layoutWidget1)
        self.imagen.setMaximumSize(QtCore.QSize(325, 150))
        self.imagen.setStyleSheet("")
        self.imagen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("../multimedia/vector.ico"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.verticalLayout.addWidget(self.imagen)
        self.titulo = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.nombreruta = QtWidgets.QLineEdit(self.splitter)
        self.nombreruta.setReadOnly(True)
        self.nombreruta.setObjectName("nombreruta")
        self.BUSCAR = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.BUSCAR.setFont(font)
        self.BUSCAR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BUSCAR.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.BUSCAR.setObjectName("BUSCAR")
        self.verticalLayout.addWidget(self.splitter)
        self.verCSV = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.verCSV.setFont(font)
        self.verCSV.setObjectName("verCSV")
        self.verticalLayout.addWidget(self.verCSV)
        self.filtrado = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.filtrado.setFont(font)
        self.filtrado.setObjectName("filtrado")
        self.verticalLayout.addWidget(self.filtrado)
        self.graficaPastel = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.graficaPastel.setFont(font)
        self.graficaPastel.setObjectName("graficaPastel")
        self.verticalLayout.addWidget(self.graficaPastel)
        self.graficaBarras = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.graficaBarras.setFont(font)
        self.graficaBarras.setObjectName("graficaBarras")
        self.verticalLayout.addWidget(self.graficaBarras)
        self.Estadistica = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.Estadistica.setFont(font)
        self.Estadistica.setObjectName("Estadistica")
        self.verticalLayout.addWidget(self.Estadistica)
        self.opciones = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.opciones.setFont(font)
        self.opciones.setObjectName("opciones")
        self.verticalLayout.addWidget(self.opciones)
        self.realizar = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.realizar.setFont(font)
        self.realizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.realizar.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.realizar.setObjectName("realizar")
        self.verticalLayout.addWidget(self.realizar)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 460, 1441, 231))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(400, 200, 341, 231))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tituloGrafica = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tituloGrafica.setFont(font)
        self.tituloGrafica.setFrameShape(QtWidgets.QFrame.Box)
        self.tituloGrafica.setText("")
        self.tituloGrafica.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloGrafica.setObjectName("tituloGrafica")
        self.verticalLayout_3.addWidget(self.tituloGrafica)
        self.titulo_Grafico = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.titulo_Grafico.setFont(font)
        self.titulo_Grafico.setPlaceholderText("")
        self.titulo_Grafico.setObjectName("titulo_Grafico")
        self.verticalLayout_3.addWidget(self.titulo_Grafico)
        self.etiqueta_nombre = QtWidgets.QLineEdit(self.layoutWidget2)
        self.etiqueta_nombre.setObjectName("etiqueta_nombre")
        self.verticalLayout_3.addWidget(self.etiqueta_nombre)
        self.etiqueta_valor = QtWidgets.QLineEdit(self.layoutWidget2)
        self.etiqueta_valor.setObjectName("etiqueta_valor")
        self.verticalLayout_3.addWidget(self.etiqueta_valor)
        self.etiqueta_usuario = QtWidgets.QLineEdit(self.layoutWidget2)
        self.etiqueta_usuario.setObjectName("etiqueta_usuario")
        self.verticalLayout_3.addWidget(self.etiqueta_usuario)
        self.etiqueta_tiempo = QtWidgets.QLineEdit(self.layoutWidget2)
        self.etiqueta_tiempo.setObjectName("etiqueta_tiempo")
        self.verticalLayout_3.addWidget(self.etiqueta_tiempo)
        self.GRAFICAR = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.GRAFICAR.setFont(font)
        self.GRAFICAR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GRAFICAR.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.GRAFICAR.setObjectName("GRAFICAR")
        self.verticalLayout_3.addWidget(self.GRAFICAR)
        self.tableDescripcion = QtWidgets.QTableWidget(self.centralwidget)
        self.tableDescripcion.setGeometry(QtCore.QRect(770, 90, 691, 341))
        self.tableDescripcion.setStyleSheet("")
        self.tableDescripcion.setObjectName("tableDescripcion")
        self.tableDescripcion.setColumnCount(0)
        self.tableDescripcion.setRowCount(0)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(1070, 12, 393, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 5, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.color_botones = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.color_botones.setFont(font)
        self.color_botones.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_botones.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}")
        self.color_botones.setObjectName("color_botones")
        self.gridLayout.addWidget(self.color_botones, 1, 1, 1, 1)
        self.color_ventanas = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.color_ventanas.setFont(font)
        self.color_ventanas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_ventanas.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.color_ventanas.setObjectName("color_ventanas")
        self.gridLayout.addWidget(self.color_ventanas, 1, 0, 1, 1)
        self.tipo_fuente = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.tipo_fuente.setFont(font)
        self.tipo_fuente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tipo_fuente.setWhatsThis("")
        self.tipo_fuente.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}")
        self.tipo_fuente.setObjectName("tipo_fuente")
        self.gridLayout.addWidget(self.tipo_fuente, 1, 2, 1, 1)
        self.hora = QtWidgets.QLCDNumber(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setItalic(True)
        self.hora.setFont(font)
        self.hora.setStyleSheet("padding:2px;\n"
"border-radius:10px;\n"
"border:3px solid black;\n"
"")
        self.hora.setObjectName("hora")
        self.gridLayout.addWidget(self.hora, 0, 1, 1, 2)
        self.cantidad_registros = QtWidgets.QLabel(self.centralwidget)
        self.cantidad_registros.setGeometry(QtCore.QRect(770, 40, 281, 41))
        self.cantidad_registros.setMinimumSize(QtCore.QSize(145, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.cantidad_registros.setFont(font)
        self.cantidad_registros.setStyleSheet("border-radius:8px;\n"
"border:1.5px solid black;")
        self.cantidad_registros.setText("")
        self.cantidad_registros.setAlignment(QtCore.Qt.AlignCenter)
        self.cantidad_registros.setObjectName("cantidad_registros")
        VentanaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(VentanaPrincipal)

    def retranslateUi(self, VentanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        VentanaPrincipal.setWindowTitle(_translate("VentanaPrincipal", "VECTOR CASA DE BOLSA SA DE CV"))
        self.titulo2.setText(_translate("VentanaPrincipal", "ENCABEZADOS DEL CSV:"))
        self.encabezados.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p align=\"center\">Aqui saldran los Encabezados del CSV</p></body></html>"))
        self.errorarchivo.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p align=\"center\">Aqui saldran los Posibles Errores</p></body></html>"))
        self.titulo.setText(_translate("VentanaPrincipal", "GRAFICAS DE PROMOCION"))
        self.BUSCAR.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Buscar Archivo CSV</span></p></body></html>"))
        self.BUSCAR.setText(_translate("VentanaPrincipal", "BUSCAR"))
        self.verCSV.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Esta opcion:</span></p><p align=\"center\">Abre el CSV y te muestra los Encabezados para despues poder Graficar</p></body></html>"))
        self.verCSV.setText(_translate("VentanaPrincipal", "Checar Encabezados y Checar el CSV"))
        self.filtrado.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Esta opcion:</span></p><p align=\"center\">Abre el CSV y te muestra los Encabezados para despues poder Graficar</p></body></html>"))
        self.filtrado.setText(_translate("VentanaPrincipal", "Filtrar CSV"))
        self.graficaPastel.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Grafica en formato Pastel:</span></p><p align=\"center\">Sirve para representar la proporcion de observaciones que estan en cada categoria.</p></body></html>"))
        self.graficaPastel.setText(_translate("VentanaPrincipal", "Graficar Pastel"))
        self.graficaBarras.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Grafica en formato Barras:</span></p><p align=\"center\">Sirve para representar o ilustrar una cantidad de datos para un mejor entendimiento de los mismos</p></body></html>"))
        self.graficaBarras.setText(_translate("VentanaPrincipal", "Graficar Barras"))
        self.Estadistica.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Estadistica Descriptiva</span></p><p align=\"center\">Se podra ver la Estadistiva Descriptiva del CSV</p></body></html>"))
        self.Estadistica.setText(_translate("VentanaPrincipal", "Ver Estadistica Descriptiva"))
        self.opciones.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Estadistica Descriptiva</span></p><p align=\"center\">Se podra ver la Estadistiva Descriptiva del CSV</p></body></html>"))
        self.opciones.setText(_translate("VentanaPrincipal", "Opciones"))
        self.realizar.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Actualizar Opcion</span></p></body></html>"))
        self.realizar.setText(_translate("VentanaPrincipal", "ACTUALIZACION"))
        self.titulo_Grafico.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Ingrese el Nombre del Grafico</span></p><p align=\"center\">(El que usted desee)</p></body></html>"))
        self.etiqueta_nombre.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Ingrese el nombre de la Etiqueta </span></p></body></html>"))
        self.etiqueta_valor.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Ingrese el nombre de la Etiqueta del valor</span></p></body></html>"))
        self.etiqueta_usuario.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Ingrese el nombre del Usuario a buscar</span></p><p align=\"center\">(Ingreselo exactamente como esta abajo)</p></body></html>"))
        self.etiqueta_tiempo.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Ingrese el nombre de la Etiqueta donde esta el Tiempo</span></p><p align=\"center\">(Las Fechas)</p></body></html>"))
        self.GRAFICAR.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p><span style=\" font-weight:600;\">Graficar CSV</span></p></body></html>"))
        self.GRAFICAR.setText(_translate("VentanaPrincipal", "GRAFICAR"))
        self.color_botones.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p>Cambiar el Color de todos los Botones</p></body></html>"))
        self.color_botones.setText(_translate("VentanaPrincipal", "COLOR BOTONES"))
        self.color_ventanas.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p>Cambiar el Color de todas las Ventanas</p></body></html>"))
        self.color_ventanas.setText(_translate("VentanaPrincipal", "COLOR VENTANAS"))
        self.tipo_fuente.setToolTip(_translate("VentanaPrincipal", "<html><head/><body><p>Cambiar el Tipo de Letra de Los Componentes</p></body></html>"))
        self.tipo_fuente.setText(_translate("VentanaPrincipal", "FUENTE LETRAS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_VentanaPrincipal()
    ui.setupUi(VentanaPrincipal)
    VentanaPrincipal.show()
    sys.exit(app.exec_())
