# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaOpciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaOpciones(object):
    def setupUi(self, VentanaOpciones):
        VentanaOpciones.setObjectName("VentanaOpciones")
        VentanaOpciones.setEnabled(True)
        VentanaOpciones.resize(450, 219)
        VentanaOpciones.setMinimumSize(QtCore.QSize(450, 219))
        VentanaOpciones.setMaximumSize(QtCore.QSize(450, 219))
        VentanaOpciones.setWindowOpacity(-4.0)
        VentanaOpciones.setStyleSheet("")
        VentanaOpciones.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(VentanaOpciones)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(0, 0, 461, 221))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setEnabled(False)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 408, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.regresar = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.regresar.setFont(font)
        self.regresar.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.regresar.setObjectName("regresar")
        self.verticalLayout.addWidget(self.regresar)
        self.titulo = QtWidgets.QLabel(self.layoutWidget)
        self.titulo.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.opciones = QtWidgets.QComboBox(self.layoutWidget)
        self.opciones.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opciones.setFont(font)
        self.opciones.setToolTip("")
        self.opciones.setStatusTip("")
        self.opciones.setWhatsThis("")
        self.opciones.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.opciones.setObjectName("opciones")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.verticalLayout.addWidget(self.opciones)
        self.elegir = QtWidgets.QPushButton(self.layoutWidget)
        self.elegir.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.elegir.setFont(font)
        self.elegir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.elegir.setStyleSheet("QPushButton{\n"
"    padding :5px;\n"
"    border-radius:10px;\n"
"    border:1.5px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(165, 175, 173);\n"
"}\n"
"\n"
"")
        self.elegir.setObjectName("elegir")
        self.verticalLayout.addWidget(self.elegir)
        self.opciones.raise_()
        self.elegir.raise_()
        self.regresar.raise_()
        self.titulo.raise_()
        VentanaOpciones.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaOpciones)
        QtCore.QMetaObject.connectSlotsByName(VentanaOpciones)

    def retranslateUi(self, VentanaOpciones):
        _translate = QtCore.QCoreApplication.translate
        VentanaOpciones.setWindowTitle(_translate("VentanaOpciones", "Opciones CSV"))
        self.regresar.setText(_translate("VentanaOpciones", "<--"))
        self.titulo.setText(_translate("VentanaOpciones", "MAS OPCIONES PARA EL CSV:"))
        self.opciones.setItemText(0, _translate("VentanaOpciones", "Eliminar Columnas"))
        self.opciones.setItemText(1, _translate("VentanaOpciones", "Eliminar Registros"))
        self.elegir.setText(_translate("VentanaOpciones", "ELEGIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaOpciones = QtWidgets.QMainWindow()
    ui = Ui_VentanaOpciones()
    ui.setupUi(VentanaOpciones)
    VentanaOpciones.show()
    sys.exit(app.exec_())
