# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnostico.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 158)
        Form.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 261, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setFrameShape(QtWidgets.QFrame.Box)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.resultado = QtWidgets.QLabel(self.widget)
        self.resultado.setFrameShape(QtWidgets.QFrame.Box)
        self.resultado.setText("")
        self.resultado.setObjectName("resultado")
        self.verticalLayout.addWidget(self.resultado)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo.setText(_translate("Form", "ELIGA EL DIAGNOSTICO A REALIZAR:"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "1-Analisis de Sangre "))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "2-Analisis de Glucosa"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "3_Analisis de Orina"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "4-Analisis de Prostata"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "5-Analisis de PH"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
