# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primera_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(267, 178)
        self.titulo2 = QtWidgets.QLabel(form)
        self.titulo2.setGeometry(QtCore.QRect(50, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setItalic(True)
        self.titulo2.setFont(font)
        self.titulo2.setFrameShape(QtWidgets.QFrame.Panel)
        self.titulo2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo2.setObjectName("titulo2")
        self.contador = QtWidgets.QLabel(form)
        self.contador.setGeometry(QtCore.QRect(80, 40, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.contador.setFont(font)
        self.contador.setTabletTracking(False)
        self.contador.setFocusPolicy(QtCore.Qt.NoFocus)
        self.contador.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contador.setFrameShape(QtWidgets.QFrame.Box)
        self.contador.setTextFormat(QtCore.Qt.PlainText)
        self.contador.setAlignment(QtCore.Qt.AlignCenter)
        self.contador.setWordWrap(False)
        self.contador.setObjectName("contador")
        self.suma = QtWidgets.QPushButton(form)
        self.suma.setGeometry(QtCore.QRect(20, 120, 101, 41))
        self.suma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.suma.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("SIGUIENT.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.suma.setIcon(icon)
        self.suma.setCheckable(False)
        self.suma.setAutoDefault(False)
        self.suma.setDefault(False)
        self.suma.setFlat(False)
        self.suma.setObjectName("suma")
        self.resta = QtWidgets.QPushButton(form)
        self.resta.setGeometry(QtCore.QRect(140, 120, 101, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("PRIMEROI.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resta.setIcon(icon1)
        self.resta.setCheckable(False)
        self.resta.setObjectName("resta")
        self.label = QtWidgets.QLabel(form)
        self.label.setGeometry(QtCore.QRect(10, 40, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("coca.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(form)
        self.label_2.setGeometry(QtCore.QRect(190, 40, 61, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("coca.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Contador_de_Cocas"))
        self.titulo2.setText(_translate("form", "¿Cuantas cocas quieres?"))
        self.contador.setText(_translate("form", "0"))
        self.suma.setText(_translate("form", "SUMAR"))
        self.resta.setText(_translate("form", "QUITAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())
