# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_simulacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Progress(object):
    def setupUi(self, Ventana_Progress):
        Ventana_Progress.setObjectName("Ventana_Progress")
        Ventana_Progress.resize(174, 107)
        self.centralwidget = QtWidgets.QWidget(Ventana_Progress)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 1)
        self.descargar = QtWidgets.QPushButton(self.frame)
        self.descargar.setObjectName("descargar")
        self.gridLayout_2.addWidget(self.descargar, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        Ventana_Progress.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ventana_Progress)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Progress)

    def retranslateUi(self, Ventana_Progress):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Progress.setWindowTitle(_translate("Ventana_Progress", "Descarga"))
        self.label.setText(_translate("Ventana_Progress", "SIMULACION DE DESCARGA"))
        self.descargar.setText(_translate("Ventana_Progress", "DESCARGA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Progress = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Progress()
    ui.setupUi(Ventana_Progress)
    Ventana_Progress.show()
    sys.exit(app.exec_())
