# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creadorbd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CREADORBD(object):
    def setupUi(self, CREADORBD):
        CREADORBD.setObjectName("CREADORBD")
        CREADORBD.resize(444, 170)
        CREADORBD.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(CREADORBD)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(110, 20, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.crearbd = QtWidgets.QPushButton(self.centralwidget)
        self.crearbd.setGeometry(QtCore.QRect(130, 120, 181, 21))
        self.crearbd.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"}")
        self.crearbd.setObjectName("crearbd")
        self.bdnombre = QtWidgets.QLineEdit(self.centralwidget)
        self.bdnombre.setGeometry(QtCore.QRect(260, 60, 141, 21))
        self.bdnombre.setObjectName("bdnombre")
        self.imagen = QtWidgets.QLabel(self.centralwidget)
        self.imagen.setGeometry(QtCore.QRect(80, 10, 31, 31))
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("CRUD/mutimedia/base.png"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.imagen_2 = QtWidgets.QLabel(self.centralwidget)
        self.imagen_2.setGeometry(QtCore.QRect(330, 10, 31, 31))
        self.imagen_2.setText("")
        self.imagen_2.setPixmap(QtGui.QPixmap("mutimedia/base.png"))
        self.imagen_2.setScaledContents(True)
        self.imagen_2.setObjectName("imagen_2")
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(10, 100, 421, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.resultado.setFont(font)
        self.resultado.setText("")
        self.resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado.setObjectName("resultado")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        CREADORBD.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CREADORBD)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 21))
        self.menubar.setObjectName("menubar")
        CREADORBD.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CREADORBD)
        self.statusbar.setObjectName("statusbar")
        CREADORBD.setStatusBar(self.statusbar)

        self.retranslateUi(CREADORBD)
        QtCore.QMetaObject.connectSlotsByName(CREADORBD)

    def retranslateUi(self, CREADORBD):
        _translate = QtCore.QCoreApplication.translate
        CREADORBD.setWindowTitle(_translate("CREADORBD", "MainWindow"))
        self.titulo.setText(_translate("CREADORBD", "CREADOR DE BASES DE DATOS"))
        self.label.setText(_translate("CREADORBD", "Ingrese el Nombre de la base de datos:"))
        self.crearbd.setText(_translate("CREADORBD", "CREAR"))
        self.bdnombre.setPlaceholderText(_translate("CREADORBD", "Preferencia Letras"))
        self.regresar.setText(_translate("CREADORBD", "<-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CREADORBD = QtWidgets.QMainWindow()
    ui = Ui_CREADORBD()
    ui.setupUi(CREADORBD)
    CREADORBD.show()
    sys.exit(app.exec_())
