# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tablas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreacionTablas(object):
    def setupUi(self, CreacionTablas):
        CreacionTablas.setObjectName("CreacionTablas")
        CreacionTablas.resize(808, 403)
        CreacionTablas.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(CreacionTablas)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(260, 0, 251, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.nombre = QtWidgets.QLabel(self.centralwidget)
        self.nombre.setGeometry(QtCore.QRect(22, 121, 161, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.nombre.setFont(font)
        self.nombre.setText("")
        self.nombre.setObjectName("nombre")
        self.nombredato = QtWidgets.QLineEdit(self.centralwidget)
        self.nombredato.setGeometry(QtCore.QRect(22, 150, 161, 20))
        self.nombredato.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nombredato.setObjectName("nombredato")
        self.tipo = QtWidgets.QComboBox(self.centralwidget)
        self.tipo.setGeometry(QtCore.QRect(200, 150, 151, 20))
        self.tipo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tipo.setObjectName("tipo")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(220, 120, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl1.setFont(font)
        self.lbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1.setObjectName("lbl1")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(10, 10, 31, 23))
        self.regresar.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.error1 = QtWidgets.QLabel(self.centralwidget)
        self.error1.setGeometry(QtCore.QRect(250, 70, 161, 21))
        self.error1.setFrameShape(QtWidgets.QFrame.Box)
        self.error1.setText("")
        self.error1.setAlignment(QtCore.Qt.AlignCenter)
        self.error1.setObjectName("error1")
        self.error2 = QtWidgets.QLabel(self.centralwidget)
        self.error2.setGeometry(QtCore.QRect(20, 180, 161, 20))
        self.error2.setFrameShape(QtWidgets.QFrame.Box)
        self.error2.setText("")
        self.error2.setAlignment(QtCore.Qt.AlignCenter)
        self.error2.setObjectName("error2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 230, 251, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error3.setFont(font)
        self.error3.setFrameShape(QtWidgets.QFrame.Box)
        self.error3.setText("")
        self.error3.setAlignment(QtCore.Qt.AlignCenter)
        self.error3.setObjectName("error3")
        self.verticalLayout.addWidget(self.error3)
        self.crear = QtWidgets.QPushButton(self.widget)
        self.crear.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}")
        self.crear.setObjectName("crear")
        self.verticalLayout.addWidget(self.crear)
        self.exito = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exito.setFont(font)
        self.exito.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.exito.setText("")
        self.exito.setAlignment(QtCore.Qt.AlignCenter)
        self.exito.setObjectName("exito")
        self.verticalLayout.addWidget(self.exito)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 40, 221, 51))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nombre_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.nombre_2.setFont(font)
        self.nombre_2.setObjectName("nombre_2")
        self.verticalLayout_3.addWidget(self.nombre_2)
        self.nombretabla = QtWidgets.QLineEdit(self.widget1)
        self.nombretabla.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nombretabla.setObjectName("nombretabla")
        self.verticalLayout_3.addWidget(self.nombretabla)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(370, 140, 77, 54))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.poner_lista = QtWidgets.QPushButton(self.widget2)
        self.poner_lista.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}")
        self.poner_lista.setObjectName("poner_lista")
        self.verticalLayout_5.addWidget(self.poner_lista)
        self.quitar_lista = QtWidgets.QPushButton(self.widget2)
        self.quitar_lista.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(170, 255, 0);\n"
"}")
        self.quitar_lista.setObjectName("quitar_lista")
        self.verticalLayout_5.addWidget(self.quitar_lista)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(460, 70, 321, 291))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.error4 = QtWidgets.QLabel(self.widget3)
        self.error4.setFrameShape(QtWidgets.QFrame.Box)
        self.error4.setText("")
        self.error4.setAlignment(QtCore.Qt.AlignCenter)
        self.error4.setObjectName("error4")
        self.verticalLayout_6.addWidget(self.error4)
        self.lbl1_2 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl1_2.setFont(font)
        self.lbl1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1_2.setObjectName("lbl1_2")
        self.verticalLayout_6.addWidget(self.lbl1_2)
        self.valores = QtWidgets.QListWidget(self.widget3)
        self.valores.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valores.setObjectName("valores")
        self.verticalLayout_6.addWidget(self.valores)
        self.tablascreadas = QtWidgets.QListWidget(self.widget3)
        self.tablascreadas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tablascreadas.setObjectName("tablascreadas")
        self.verticalLayout_6.addWidget(self.tablascreadas)
        self.borrar = QtWidgets.QPushButton(self.widget3)
        self.borrar.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}")
        self.borrar.setObjectName("borrar")
        self.verticalLayout_6.addWidget(self.borrar)
        CreacionTablas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreacionTablas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 21))
        self.menubar.setObjectName("menubar")
        CreacionTablas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreacionTablas)
        self.statusbar.setObjectName("statusbar")
        CreacionTablas.setStatusBar(self.statusbar)

        self.retranslateUi(CreacionTablas)
        self.borrar.clicked.connect(self.valores.clear)
        self.quitar_lista.clicked.connect(self.valores.clear)
        QtCore.QMetaObject.connectSlotsByName(CreacionTablas)

    def retranslateUi(self, CreacionTablas):
        _translate = QtCore.QCoreApplication.translate
        CreacionTablas.setWindowTitle(_translate("CreacionTablas", "MainWindow"))
        self.titulo.setText(_translate("CreacionTablas", "CREADOR DE TABLAS"))
        self.nombredato.setPlaceholderText(_translate("CreacionTablas", "Ingrese valores alfanumericos"))
        self.tipo.setItemText(0, _translate("CreacionTablas", "INTEGER PRIMARY KEY"))
        self.tipo.setItemText(1, _translate("CreacionTablas", "TEXT PRIMARY KEY"))
        self.tipo.setItemText(2, _translate("CreacionTablas", "TEXT"))
        self.tipo.setItemText(3, _translate("CreacionTablas", "INTEGER"))
        self.lbl1.setText(_translate("CreacionTablas", "Tipo de Valor:"))
        self.regresar.setText(_translate("CreacionTablas", "<-"))
        self.crear.setText(_translate("CreacionTablas", "CREAR"))
        self.nombre_2.setText(_translate("CreacionTablas", "Ingrese el Nombre de la Tabla:"))
        self.nombretabla.setPlaceholderText(_translate("CreacionTablas", "Ingrese valores alfanumericos"))
        self.poner_lista.setText(_translate("CreacionTablas", "->"))
        self.quitar_lista.setText(_translate("CreacionTablas", "<-"))
        self.lbl1_2.setText(_translate("CreacionTablas", "VISUALIZADOR"))
        self.borrar.setText(_translate("CreacionTablas", "BORRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreacionTablas = QtWidgets.QMainWindow()
    ui = Ui_CreacionTablas()
    ui.setupUi(CreacionTablas)
    CreacionTablas.show()
    sys.exit(app.exec_())
