# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaP2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaP2(object):
    def setupUi(self, VentanaP2):
        VentanaP2.setObjectName("VentanaP2")
        VentanaP2.resize(318, 257)
        VentanaP2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(VentanaP2)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(30, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setFrameShape(QtWidgets.QFrame.Box)
        self.titulo.setText("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(10, 10, 41, 23))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.opciones = QtWidgets.QComboBox(self.centralwidget)
        self.opciones.setGeometry(QtCore.QRect(20, 90, 121, 21))
        self.opciones.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.opciones.setObjectName("opciones")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.opciones.addItem("")
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(180, 90, 75, 23))
        self.enter.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.enter.setObjectName("enter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 130, 151, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("mutimedia/base2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        VentanaP2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaP2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menubar.setObjectName("menubar")
        VentanaP2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaP2)
        self.statusbar.setObjectName("statusbar")
        VentanaP2.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaP2)
        QtCore.QMetaObject.connectSlotsByName(VentanaP2)

    def retranslateUi(self, VentanaP2):
        _translate = QtCore.QCoreApplication.translate
        VentanaP2.setWindowTitle(_translate("VentanaP2", "MainWindow"))
        self.regresar.setText(_translate("VentanaP2", "<-"))
        self.opciones.setItemText(0, _translate("VentanaP2", "CREAR TABLAS"))
        self.opciones.setItemText(1, _translate("VentanaP2", "VER TABLAS"))
        self.opciones.setItemText(2, _translate("VentanaP2", "ELIMINAR TABLAS"))
        self.opciones.setItemText(3, _translate("VentanaP2", "ALTA"))
        self.opciones.setItemText(4, _translate("VentanaP2", "BAJA"))
        self.opciones.setItemText(5, _translate("VentanaP2", "CAMBIO"))
        self.opciones.setItemText(6, _translate("VentanaP2", "SELECCIONAR"))
        self.opciones.setItemText(7, _translate("VentanaP2", "PDF"))
        self.opciones.setItemText(8, _translate("VentanaP2", "TXT"))
        self.opciones.setItemText(9, _translate("VentanaP2", "CSV"))
        self.opciones.setItemText(10, _translate("VentanaP2", "GRAFICAR PASTEL"))
        self.opciones.setItemText(11, _translate("VentanaP2", "GRAFICAR BARRAS"))
        self.enter.setText(_translate("VentanaP2", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaP2 = QtWidgets.QMainWindow()
    ui = Ui_VentanaP2()
    ui.setupUi(VentanaP2)
    VentanaP2.show()
    sys.exit(app.exec_())
