# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaVCSV.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaValidacionCSV(object):
    def setupUi(self, VentanaValidacionCSV):
        VentanaValidacionCSV.setObjectName("VentanaValidacionCSV")
        VentanaValidacionCSV.resize(399, 252)
        VentanaValidacionCSV.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(VentanaValidacionCSV)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 301, 205))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.regresar = QtWidgets.QPushButton(self.layoutWidget)
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.verticalLayout.addWidget(self.regresar)
        self.titulo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.error1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.error1.setFont(font)
        self.error1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.error1.setText("")
        self.error1.setAlignment(QtCore.Qt.AlignCenter)
        self.error1.setObjectName("error1")
        self.verticalLayout.addWidget(self.error1)
        self.tablascreadas = QtWidgets.QListWidget(self.layoutWidget)
        self.tablascreadas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tablascreadas.setObjectName("tablascreadas")
        self.verticalLayout.addWidget(self.tablascreadas)
        self.nombretabla = QtWidgets.QLineEdit(self.layoutWidget)
        self.nombretabla.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nombretabla.setObjectName("nombretabla")
        self.verticalLayout.addWidget(self.nombretabla)
        self.enviar = QtWidgets.QPushButton(self.layoutWidget)
        self.enviar.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.enviar.setObjectName("enviar")
        self.verticalLayout.addWidget(self.enviar)
        VentanaValidacionCSV.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaValidacionCSV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 399, 21))
        self.menubar.setObjectName("menubar")
        VentanaValidacionCSV.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaValidacionCSV)
        self.statusbar.setObjectName("statusbar")
        VentanaValidacionCSV.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaValidacionCSV)
        QtCore.QMetaObject.connectSlotsByName(VentanaValidacionCSV)

    def retranslateUi(self, VentanaValidacionCSV):
        _translate = QtCore.QCoreApplication.translate
        VentanaValidacionCSV.setWindowTitle(_translate("VentanaValidacionCSV", "MainWindow"))
        self.regresar.setText(_translate("VentanaValidacionCSV", "<-"))
        self.titulo.setText(_translate("VentanaValidacionCSV", "En que tabla desea hacer un Reporte CSV:"))
        self.nombretabla.setPlaceholderText(_translate("VentanaValidacionCSV", "Ingrese el nombre de la Tabla (Las Opciones de arriba)"))
        self.enviar.setText(_translate("VentanaValidacionCSV", "ENTRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaValidacionCSV = QtWidgets.QMainWindow()
    ui = Ui_VentanaValidacionCSV()
    ui.setupUi(VentanaValidacionCSV)
    VentanaValidacionCSV.show()
    sys.exit(app.exec_())
