# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaP2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaP2(object):
    def setupUi(self, VentanaP2):
        VentanaP2.setObjectName("VentanaP2")
        VentanaP2.resize(318, 257)
        VentanaP2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(VentanaP2)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(30, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setFrameShape(QtWidgets.QFrame.Box)
        self.titulo.setText("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(10, 10, 41, 23))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.opciones = QtWidgets.QComboBox(self.centralwidget)
        self.opciones.setGeometry(QtCore.QRect(20, 90, 121, 21))
        self.opciones.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.opciones.setObjectName("opciones")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CRUD/mutimedia/crear_tabla.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("CRUD/mutimedia/eliminar_tabla.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("CRUD/mutimedia/ver_tablas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("CRUD/mutimedia/insertar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("CRUD/mutimedia/borrar_registro.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("CRUD/mutimedia/cambiar_registro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("CRUD/mutimedia/buscar_registro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("CRUD/mutimedia/txt2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("CRUD/mutimedia/csv2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opciones.addItem(icon8, "")
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(180, 90, 75, 23))
        self.enter.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("CRUD/mutimedia/entrar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enter.setIcon(icon9)
        self.enter.setObjectName("enter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 130, 151, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("CRUD/mutimedia/base2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        VentanaP2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaP2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menubar.setObjectName("menubar")
        VentanaP2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaP2)
        self.statusbar.setObjectName("statusbar")
        VentanaP2.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaP2)
        QtCore.QMetaObject.connectSlotsByName(VentanaP2)

    def retranslateUi(self, VentanaP2):
        _translate = QtCore.QCoreApplication.translate
        VentanaP2.setWindowTitle(_translate("VentanaP2", "MainWindow"))
        self.regresar.setText(_translate("VentanaP2", "<-"))
        self.opciones.setItemText(0, _translate("VentanaP2", "CREAR TABLAS"))
        self.opciones.setItemText(1, _translate("VentanaP2", "ELIMINAR TABLAS"))
        self.opciones.setItemText(2, _translate("VentanaP2", "VER TABLAS"))
        self.opciones.setItemText(3, _translate("VentanaP2", "ALTA"))
        self.opciones.setItemText(4, _translate("VentanaP2", "BAJA"))
        self.opciones.setItemText(5, _translate("VentanaP2", "CAMBIO"))
        self.opciones.setItemText(6, _translate("VentanaP2", "SELECCIONAR"))
        self.opciones.setItemText(7, _translate("VentanaP2", "TXT"))
        self.opciones.setItemText(8, _translate("VentanaP2", "CSV"))
        self.enter.setText(_translate("VentanaP2", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaP2 = QtWidgets.QMainWindow()
    ui = Ui_VentanaP2()
    ui.setupUi(VentanaP2)
    VentanaP2.show()
    sys.exit(app.exec_())
