# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaVTablas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaVisualizadoraTablas(object):
    def setupUi(self, VentanaVisualizadoraTablas):
        VentanaVisualizadoraTablas.setObjectName("VentanaVisualizadoraTablas")
        VentanaVisualizadoraTablas.setWindowModality(QtCore.Qt.NonModal)
        VentanaVisualizadoraTablas.resize(408, 308)
        VentanaVisualizadoraTablas.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(VentanaVisualizadoraTablas)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 351, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.regresar = QtWidgets.QPushButton(self.layoutWidget)
        self.regresar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(85, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.verticalLayout.addWidget(self.regresar)
        self.titulo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.nombrestablas = QtWidgets.QListWidget(self.layoutWidget)
        self.nombrestablas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nombrestablas.setObjectName("nombrestablas")
        self.verticalLayout.addWidget(self.nombrestablas)
        self.numerotablas = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numerotablas.setFont(font)
        self.numerotablas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.numerotablas.setFrameShape(QtWidgets.QFrame.Box)
        self.numerotablas.setText("")
        self.numerotablas.setAlignment(QtCore.Qt.AlignCenter)
        self.numerotablas.setObjectName("numerotablas")
        self.verticalLayout.addWidget(self.numerotablas)
        VentanaVisualizadoraTablas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaVisualizadoraTablas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 408, 21))
        self.menubar.setObjectName("menubar")
        VentanaVisualizadoraTablas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaVisualizadoraTablas)
        self.statusbar.setObjectName("statusbar")
        VentanaVisualizadoraTablas.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaVisualizadoraTablas)
        QtCore.QMetaObject.connectSlotsByName(VentanaVisualizadoraTablas)

    def retranslateUi(self, VentanaVisualizadoraTablas):
        _translate = QtCore.QCoreApplication.translate
        VentanaVisualizadoraTablas.setWindowTitle(_translate("VentanaVisualizadoraTablas", "MainWindow"))
        self.regresar.setText(_translate("VentanaVisualizadoraTablas", "<-"))
        self.titulo.setText(_translate("VentanaVisualizadoraTablas", "VISUALIZADOR DE TABLAS CREADAS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaVisualizadoraTablas = QtWidgets.QMainWindow()
    ui = Ui_VentanaVisualizadoraTablas()
    ui.setupUi(VentanaVisualizadoraTablas)
    VentanaVisualizadoraTablas.show()
    sys.exit(app.exec_())
