# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaCSV.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaHacerCsv(object):
    def setupUi(self, VentanaHacerCsv):
        VentanaHacerCsv.setObjectName("VentanaHacerCsv")
        VentanaHacerCsv.resize(532, 287)
        VentanaHacerCsv.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.centralwidget = QtWidgets.QWidget(VentanaHacerCsv)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(150, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(242, 160, 21, 111))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(226, 200, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.imagen2 = QtWidgets.QLabel(self.centralwidget)
        self.imagen2.setGeometry(QtCore.QRect(210, 80, 81, 71))
        self.imagen2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagen2.setFrameShape(QtWidgets.QFrame.Box)
        self.imagen2.setText("")
        self.imagen2.setPixmap(QtGui.QPixmap("CRUD/mutimedia/csv.png"))
        self.imagen2.setScaledContents(True)
        self.imagen2.setObjectName("imagen2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 491, 20))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 40, 21, 231))
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.mensaje = QtWidgets.QLabel(self.centralwidget)
        self.mensaje.setGeometry(QtCore.QRect(130, 50, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.mensaje.setFont(font)
        self.mensaje.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mensaje.setFrameShape(QtWidgets.QFrame.Box)
        self.mensaje.setText("")
        self.mensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje.setObjectName("mensaje")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(490, 40, 21, 241))
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 160, 201, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nombrecampo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.nombrecampo.setFont(font)
        self.nombrecampo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nombrecampo.setText("")
        self.nombrecampo.setAlignment(QtCore.Qt.AlignCenter)
        self.nombrecampo.setObjectName("nombrecampo")
        self.verticalLayout_2.addWidget(self.nombrecampo)
        self.datoabuscar = QtWidgets.QLineEdit(self.layoutWidget)
        self.datoabuscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.datoabuscar.setInputMask("")
        self.datoabuscar.setText("")
        self.datoabuscar.setAlignment(QtCore.Qt.AlignCenter)
        self.datoabuscar.setObjectName("datoabuscar")
        self.verticalLayout_2.addWidget(self.datoabuscar)
        self.hacertcsv = QtWidgets.QPushButton(self.layoutWidget)
        self.hacertcsv.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.hacertcsv.setObjectName("hacertcsv")
        self.verticalLayout_2.addWidget(self.hacertcsv)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 160, 201, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setItalic(True)
        self.titulo2.setFont(font)
        self.titulo2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo2.setObjectName("titulo2")
        self.verticalLayout.addWidget(self.titulo2)
        self.combocampos = QtWidgets.QComboBox(self.layoutWidget1)
        self.combocampos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.combocampos.setObjectName("combocampos")
        self.verticalLayout.addWidget(self.combocampos)
        self.elegir = QtWidgets.QPushButton(self.layoutWidget1)
        self.elegir.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 170, 255);\n"
"        color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.elegir.setObjectName("elegir")
        self.verticalLayout.addWidget(self.elegir)
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(40, 10, 61, 23))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.regresar.setObjectName("regresar")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.titulo.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.imagen2.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.mensaje.raise_()
        self.line_4.raise_()
        self.regresar.raise_()
        VentanaHacerCsv.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaHacerCsv)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menubar.setObjectName("menubar")
        VentanaHacerCsv.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaHacerCsv)
        self.statusbar.setObjectName("statusbar")
        VentanaHacerCsv.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaHacerCsv)
        QtCore.QMetaObject.connectSlotsByName(VentanaHacerCsv)

    def retranslateUi(self, VentanaHacerCsv):
        _translate = QtCore.QCoreApplication.translate
        VentanaHacerCsv.setWindowTitle(_translate("VentanaHacerCsv", "MainWindow"))
        self.titulo.setText(_translate("VentanaHacerCsv", "REPORTE CSV:"))
        self.label_2.setText(_translate("VentanaHacerCsv", "---"))
        self.label_4.setText(_translate("VentanaHacerCsv", ">"))
        self.datoabuscar.setPlaceholderText(_translate("VentanaHacerCsv", "Ingresa el nombre o numero a buscar"))
        self.hacertcsv.setText(_translate("VentanaHacerCsv", "Convertir a CSV"))
        self.titulo2.setText(_translate("VentanaHacerCsv", "Elegi el Campo a buscar:"))
        self.elegir.setText(_translate("VentanaHacerCsv", "ELEGIR"))
        self.regresar.setText(_translate("VentanaHacerCsv", "<---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaHacerCsv = QtWidgets.QMainWindow()
    ui = Ui_VentanaHacerCsv()
    ui.setupUi(VentanaHacerCsv)
    VentanaHacerCsv.show()
    sys.exit(app.exec_())
