# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaTXT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaHacerTxt(object):
    def setupUi(self, VentanaHacerTxt):
        VentanaHacerTxt.setObjectName("VentanaHacerTxt")
        VentanaHacerTxt.resize(532, 287)
        VentanaHacerTxt.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(VentanaHacerTxt)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(150, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(242, 80, 21, 191))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(226, 170, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.imagen = QtWidgets.QLabel(self.centralwidget)
        self.imagen.setGeometry(QtCore.QRect(330, 80, 121, 71))
        self.imagen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagen.setFrameShape(QtWidgets.QFrame.Box)
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("CRUD/mutimedia/txtLleno.png"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.imagen2 = QtWidgets.QLabel(self.centralwidget)
        self.imagen2.setGeometry(QtCore.QRect(60, 80, 121, 71))
        self.imagen2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagen2.setFrameShape(QtWidgets.QFrame.Box)
        self.imagen2.setText("")
        self.imagen2.setPixmap(QtGui.QPixmap("CRUD/mutimedia/txtvacio.png"))
        self.imagen2.setScaledContents(True)
        self.imagen2.setObjectName("imagen2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 491, 20))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 40, 21, 231))
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.mensaje = QtWidgets.QLabel(self.centralwidget)
        self.mensaje.setGeometry(QtCore.QRect(150, 50, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.mensaje.setFont(font)
        self.mensaje.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mensaje.setFrameShape(QtWidgets.QFrame.Box)
        self.mensaje.setText("")
        self.mensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje.setObjectName("mensaje")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 260, 501, 20))
        self.line_5.setStyleSheet("")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(490, 40, 21, 241))
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 160, 201, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nombrecampo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.nombrecampo.setFont(font)
        self.nombrecampo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nombrecampo.setText("")
        self.nombrecampo.setAlignment(QtCore.Qt.AlignCenter)
        self.nombrecampo.setObjectName("nombrecampo")
        self.verticalLayout_2.addWidget(self.nombrecampo)
        self.datoabuscar = QtWidgets.QLineEdit(self.layoutWidget)
        self.datoabuscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.datoabuscar.setInputMask("")
        self.datoabuscar.setText("")
        self.datoabuscar.setAlignment(QtCore.Qt.AlignCenter)
        self.datoabuscar.setObjectName("datoabuscar")
        self.verticalLayout_2.addWidget(self.datoabuscar)
        self.hacertxt = QtWidgets.QPushButton(self.layoutWidget)
        self.hacertxt.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 0, 255);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.hacertxt.setObjectName("hacertxt")
        self.verticalLayout_2.addWidget(self.hacertxt)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 160, 201, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setItalic(True)
        self.titulo2.setFont(font)
        self.titulo2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo2.setObjectName("titulo2")
        self.verticalLayout.addWidget(self.titulo2)
        self.combocampos = QtWidgets.QComboBox(self.layoutWidget1)
        self.combocampos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.combocampos.setObjectName("combocampos")
        self.verticalLayout.addWidget(self.combocampos)
        self.elegir = QtWidgets.QPushButton(self.layoutWidget1)
        self.elegir.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.elegir.setObjectName("elegir")
        self.verticalLayout.addWidget(self.elegir)
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(40, 10, 61, 23))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.regresar.setObjectName("regresar")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.titulo.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.imagen.raise_()
        self.imagen2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.mensaje.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.regresar.raise_()
        VentanaHacerTxt.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaHacerTxt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menubar.setObjectName("menubar")
        VentanaHacerTxt.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaHacerTxt)
        self.statusbar.setObjectName("statusbar")
        VentanaHacerTxt.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaHacerTxt)
        QtCore.QMetaObject.connectSlotsByName(VentanaHacerTxt)

    def retranslateUi(self, VentanaHacerTxt):
        _translate = QtCore.QCoreApplication.translate
        VentanaHacerTxt.setWindowTitle(_translate("VentanaHacerTxt", "MainWindow"))
        self.titulo.setText(_translate("VentanaHacerTxt", "REPORTE TXT:"))
        self.label_2.setText(_translate("VentanaHacerTxt", "---"))
        self.label_4.setText(_translate("VentanaHacerTxt", ">"))
        self.label_3.setText(_translate("VentanaHacerTxt", "---"))
        self.label_5.setText(_translate("VentanaHacerTxt", ">"))
        self.datoabuscar.setPlaceholderText(_translate("VentanaHacerTxt", "Ingresa el nombre o numero a buscar"))
        self.hacertxt.setText(_translate("VentanaHacerTxt", "Convertir a TXT"))
        self.titulo2.setText(_translate("VentanaHacerTxt", "Elegi el Campo a buscar:"))
        self.elegir.setText(_translate("VentanaHacerTxt", "ELEGIR"))
        self.regresar.setText(_translate("VentanaHacerTxt", "<---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaHacerTxt = QtWidgets.QMainWindow()
    ui = Ui_VentanaHacerTxt()
    ui.setupUi(VentanaHacerTxt)
    VentanaHacerTxt.show()
    sys.exit(app.exec_())
