# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaP1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaP(object):
    def setupUi(self, VentanaP):
        VentanaP.setObjectName("VentanaP")
        VentanaP.resize(243, 475)
        VentanaP.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(VentanaP)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 204, 432))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.imagen = QtWidgets.QLabel(self.layoutWidget)
        self.imagen.setFrameShape(QtWidgets.QFrame.Box)
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap("mutimedia/base.png"))
        self.imagen.setScaledContents(True)
        self.imagen.setWordWrap(False)
        self.imagen.setObjectName("imagen")
        self.verticalLayout.addWidget(self.imagen)
        self.nombrebd = QtWidgets.QLineEdit(self.layoutWidget)
        self.nombrebd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nombrebd.setObjectName("nombrebd")
        self.verticalLayout.addWidget(self.nombrebd)
        self.ingresar = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ingresar.setFont(font)
        self.ingresar.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 85, 255);\n"
"}")
        self.ingresar.setObjectName("ingresar")
        self.verticalLayout.addWidget(self.ingresar)
        self.crearbd = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.crearbd.setFont(font)
        self.crearbd.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.crearbd.setObjectName("crearbd")
        self.verticalLayout.addWidget(self.crearbd)
        self.informacion = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.informacion.setFont(font)
        self.informacion.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.informacion.setObjectName("informacion")
        self.verticalLayout.addWidget(self.informacion)
        self.salir = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.salir.setFont(font)
        self.salir.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"}")
        self.salir.setObjectName("salir")
        self.verticalLayout.addWidget(self.salir)
        VentanaP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 243, 21))
        self.menubar.setObjectName("menubar")
        VentanaP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaP)
        self.statusbar.setObjectName("statusbar")
        VentanaP.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaP)
        self.salir.clicked.connect(VentanaP.close)
        QtCore.QMetaObject.connectSlotsByName(VentanaP)

    def retranslateUi(self, VentanaP):
        _translate = QtCore.QCoreApplication.translate
        VentanaP.setWindowTitle(_translate("VentanaP", "MainWindow"))
        self.label.setText(_translate("VentanaP", "BASE DE DATOS "))
        self.nombrebd.setPlaceholderText(_translate("VentanaP", "Ingrese el nombre de la Base de Datos"))
        self.ingresar.setText(_translate("VentanaP", "ENTRAR"))
        self.crearbd.setText(_translate("VentanaP", "CREAR"))
        self.informacion.setText(_translate("VentanaP", "INFORMACION"))
        self.salir.setText(_translate("VentanaP", "SALIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaP = QtWidgets.QMainWindow()
    ui = Ui_VentanaP()
    ui.setupUi(VentanaP)
    VentanaP.show()
    sys.exit(app.exec_())
