# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaInformacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventanainformacion(object):
    def setupUi(self, Ventanainformacion):
        Ventanainformacion.setObjectName("Ventanainformacion")
        Ventanainformacion.resize(587, 321)
        Ventanainformacion.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(Ventanainformacion)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(20, 10, 551, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.requerimientos = QtWidgets.QListWidget(self.centralwidget)
        self.requerimientos.setGeometry(QtCore.QRect(170, 40, 256, 81))
        self.requerimientos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.requerimientos.setObjectName("requerimientos")
        item = QtWidgets.QListWidgetItem()
        self.requerimientos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.requerimientos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.requerimientos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.requerimientos.addItem(item)
        self.foto = QtWidgets.QLabel(self.centralwidget)
        self.foto.setGeometry(QtCore.QRect(10, 150, 131, 141))
        self.foto.setFrameShape(QtWidgets.QFrame.Box)
        self.foto.setText("")
        self.foto.setPixmap(QtGui.QPixmap("CRUD/mutimedia/daniel.gif"))
        self.foto.setScaledContents(True)
        self.foto.setObjectName("foto")
        self.regresar = QtWidgets.QPushButton(self.centralwidget)
        self.regresar.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.regresar.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.regresar.setObjectName("regresar")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 150, 431, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.GIT = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.GIT.setFont(font)
        self.GIT.setStyleSheet("QPushButton:hover{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.GIT.setObjectName("GIT")
        self.verticalLayout.addWidget(self.GIT)
        self.FACE = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.FACE.setFont(font)
        self.FACE.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.FACE.setObjectName("FACE")
        self.verticalLayout.addWidget(self.FACE)
        Ventanainformacion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ventanainformacion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        Ventanainformacion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ventanainformacion)
        self.statusbar.setObjectName("statusbar")
        Ventanainformacion.setStatusBar(self.statusbar)

        self.retranslateUi(Ventanainformacion)
        QtCore.QMetaObject.connectSlotsByName(Ventanainformacion)

    def retranslateUi(self, Ventanainformacion):
        _translate = QtCore.QCoreApplication.translate
        Ventanainformacion.setWindowTitle(_translate("Ventanainformacion", "MainWindow"))
        self.titulo.setText(_translate("Ventanainformacion", "REQUERIMIENTOS NECESARIOS PARA PODER EJECUTAR CORRECTAMENTE ESTA APLICACION(GUI) "))
        __sortingEnabled = self.requerimientos.isSortingEnabled()
        self.requerimientos.setSortingEnabled(False)
        item = self.requerimientos.item(0)
        item.setText(_translate("Ventanainformacion", "1- Tener instalado PyQT5"))
        item = self.requerimientos.item(1)
        item.setText(_translate("Ventanainformacion", "2- Tener instalado Python"))
        item = self.requerimientos.item(2)
        item.setText(_translate("Ventanainformacion", "3- Tener instalado Matplotlib"))
        item = self.requerimientos.item(3)
        item.setText(_translate("Ventanainformacion", "4- Tener instalado SqLite3"))
        self.requerimientos.setSortingEnabled(__sortingEnabled)
        self.regresar.setText(_translate("Ventanainformacion", "<-"))
        self.label.setText(_translate("Ventanainformacion", "DESAROLLADO POR:"))
        self.label_2.setText(_translate("Ventanainformacion", "DANIEL EDUARDO ROJAS GARZA"))
        self.label_3.setText(_translate("Ventanainformacion", "Lic.Tecnologias de la Informacion"))
        self.GIT.setText(_translate("Ventanainformacion", "LIGA GITHUB"))
        self.FACE.setText(_translate("Ventanainformacion", "LIGA FACEBOOK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventanainformacion = QtWidgets.QMainWindow()
    ui = Ui_Ventanainformacion()
    ui.setupUi(Ventanainformacion)
    Ventanainformacion.show()
    sys.exit(app.exec_())
