# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(195, 131)
        self.datos = QtWidgets.QComboBox(Form)
        self.datos.setGeometry(QtCore.QRect(20, 20, 161, 22))
        self.datos.setObjectName("datos")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("multimedia/python.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("multimedia/c++.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("multimedia/css.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("multimedia/html.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("multimedia/java.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("multimedia/javascript.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("multimedia/r.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos.addItem(icon6, "")
        self.enviar = QtWidgets.QPushButton(Form)
        self.enviar.setGeometry(QtCore.QRect(50, 60, 75, 23))
        self.enviar.setObjectName("enviar")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 100, 151, 20))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.datos.setItemText(0, _translate("Form", "Python"))
        self.datos.setItemText(1, _translate("Form", "C++"))
        self.datos.setItemText(2, _translate("Form", "CSS"))
        self.datos.setItemText(3, _translate("Form", "HTML"))
        self.datos.setItemText(4, _translate("Form", "Java"))
        self.datos.setItemText(5, _translate("Form", "Javascript"))
        self.datos.setItemText(6, _translate("Form", "R"))
        self.enviar.setText(_translate("Form", "Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
